"""
api/pdf_report.py — generates a downloadable PDF summary of a scan result.

Pure function (dict in, PDF bytes out) so it's testable without needing
a live scan — feed it the same shape run_scan() returns and it'll build
a report from it.
"""

import io
from datetime import datetime, timezone

from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
)

GRADE_COLORS = {
    "A+": colors.HexColor("#2F6F4E"), "A": colors.HexColor("#2F6F4E"), "A-": colors.HexColor("#2F6F4E"),
    "B+": colors.HexColor("#9C6B0B"), "B": colors.HexColor("#9C6B0B"), "B-": colors.HexColor("#9C6B0B"),
    "C+": colors.HexColor("#9C6B0B"), "C": colors.HexColor("#9C6B0B"), "C-": colors.HexColor("#9C6B0B"),
    "D": colors.HexColor("#A33B2B"), "F": colors.HexColor("#A33B2B"),
}


def build_pdf(scan_result: dict) -> bytes:
    """
    Build a PDF summary of a completed scan.

    Args:
        scan_result: the dict returned by celery_worker.run_scan(), i.e.
                      {"url": ..., "headers": ..., "ssl": ..., "cms": ...,
                       "report": {"score", "grade", "breakdown", "max_breakdown",
                                  "passed_checks", "failed_checks"}}

    Returns:
        raw PDF file bytes.
    """
    report = scan_result["report"]
    url = scan_result["url"]

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=LETTER,
        topMargin=0.75 * inch, bottomMargin=0.75 * inch,
        leftMargin=0.75 * inch, rightMargin=0.75 * inch,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("ReportTitle", parent=styles["Heading1"], fontSize=20, spaceAfter=4)
    url_style = ParagraphStyle("URL", parent=styles["Normal"], fontSize=10, textColor=colors.grey, spaceAfter=16)
    score_style = ParagraphStyle(
        "Score", parent=styles["Heading1"], fontSize=36, spaceAfter=16, leading=42,
        textColor=GRADE_COLORS.get(report["grade"], colors.black),
    )
    section_style = ParagraphStyle("Section", parent=styles["Heading2"], fontSize=13, spaceBefore=16, spaceAfter=6)
    check_style = ParagraphStyle("Check", parent=styles["Normal"], fontSize=10, spaceAfter=2)
    fix_style = ParagraphStyle("Fix", parent=styles["Normal"], fontSize=9, textColor=colors.grey,
                                leftIndent=14, spaceAfter=8)

    elements = []
    elements.append(Paragraph("VulnScan Lite — Security Health Report", title_style))
    elements.append(Paragraph(url, url_style))
    elements.append(Paragraph(f"{report['score']} / 100 &nbsp;&nbsp; Grade: {report['grade']}", score_style))

    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    elements.append(Paragraph(f"Generated {generated}", url_style))

    # --- breakdown table ---
    elements.append(Paragraph("Score breakdown", section_style))
    breakdown_data = [["Category", "Points"]]
    for key, label in [("headers", "Security Headers"), ("ssl", "SSL/TLS"), ("cms", "CMS/Software")]:
        earned = report["breakdown"].get(key, 0)
        max_pts = report["max_breakdown"].get(key, 0)
        breakdown_data.append([label, f"{earned} / {max_pts}"])

    table = Table(breakdown_data, colWidths=[3.5 * inch, 2 * inch])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1E2A38")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#C7CCC4")),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(table)

    # --- passed checks ---
    if report["passed_checks"]:
        elements.append(Paragraph("Passed checks", section_style))
        for item in report["passed_checks"]:
            text = item["check"]
            if item.get("value"):
                text += f" — {item['value']}"
            elements.append(Paragraph(f"✓ {text}", check_style))

    # --- failed checks ---
    if report["failed_checks"]:
        elements.append(Paragraph("Needs attention", section_style))
        for item in report["failed_checks"]:
            elements.append(Paragraph(f"✗  {item['check']}", check_style))
            if item.get("how_to_fix"):
                elements.append(Paragraph(item["how_to_fix"].replace("\n", "<br/>"), fix_style))

    elements.append(Spacer(1, 20))
    elements.append(Paragraph(
        "Generated by VulnScan Lite — passive analysis only. "
        "Only scan websites you own.",
        ParagraphStyle("Footer", parent=styles["Normal"], fontSize=8, textColor=colors.grey),
    ))

    doc.build(elements)
    return buffer.getvalue()
